# -*- coding: utf-8 -*-
"""cv6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U36oWTexDkniNRsgAws53odXU1ObzCSh
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

rmin = 100
rmax = 200
img = cv2.imread("/content/images3.jpg",0)
original_color_img_for_display = cv2.imread("/content/images3.jpg")
original_color_img_for_display_rgb = cv2.cvtColor(original_color_img_for_display, cv2.COLOR_BGR2RGB)

slice_with_bg = img.copy()
slice_without_bg = np.zeros(img.shape, dtype=img.dtype)

for i in range(img.shape[0]):
  for j in range(img.shape[1]):
    pixel_value = img[i, j]
    if rmin <= pixel_value <= rmax:
      slice_without_bg[i, j] = 255
    else:
      slice_with_bg[i, j] = 0
      slice_without_bg[i, j] = 0

plt.figure(figsize=(15, 5))
plt.subplot(1, 3, 1)
plt.imshow(original_color_img_for_display_rgb)
plt.title('Original Image (Color)')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(slice_with_bg, cmap='gray')
plt.title('Slice with Background ')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(slice_without_bg, cmap='gray')
plt.title('Slice Without Background')
plt.axis('off')

plt.show()